### ISSUE TITLE
The accuracy of CoEx

### ISSUE THREAD

**Issue by cocowy1** [gangweiX/Fast-ACVNet#2]
Hello,  as for the comparison result of CoEx, its accuracy is 2.02% (kitti15 d1_all) and the running time is 0.027s (2080ti).

**Comment by gangweix** [comment]
The result of CoEx is from the published paper, Correlate-and-Excite: Real-Time Stereo Matching via Guided Cost Volume Excitation. The inference time is tested on our device.
