### ISSUE TITLE
Fast_ACVNet and Fast_ACVNet_plus

### ISSUE THREAD

**Issue by Torment123** [gangweiX/Fast-ACVNet#6]
Hi, I noticed that there's a fast_acvnet_plus in the model folder, which is implemented differently compare to the paper (the correlation is computed between feature maps of 1/4 of the original resolution instead of 1/8), So if I want to reproduce the result of fast_acvnet, I think I should instead use the model in Fast_ACV.py ? Also, what benefit of fast_acvnet_plus compare to the vanilla fast_acvnet? Thanks in davance

**Comment by gangweix** [comment]
Thank you for your attention. The fast_acvnet_plus constructs a higher resolution correlation  (i.e. 1/4), which can obtain more accurate attention weights.

**Comment by Torment123** [comment]
I see, thanks for your fast reponse
